### PR TITLE
Hologram:setFlexWeight is going to work fine now

### PR DESCRIPTION
**Pull request by vintproykt**
Awaiting hotfix approval.

### CODE REVIEW

**Comment by thegrb93** [comment]
Something you're doing isn't right because there's a million commits in every pr you make.

**Comment by Damianu** [comment]
yeah, you should create separate branch for each PR or merge&rebase your fork to fit upstream to fix that on master(you need CLI for that).

**Comment by vintproykt** [comment]
@thegrb93 Dude, I just was talking about it on Discord.
@Damianu Gah, I don't understand how to rebase my remote fork on GitHub.

**Comment by CornerPin** [comment]
Have you tried this https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa?

**Pull request merged**
