### PR TITLE
Projected Textures for Starfall

### LINKED ISSUE #1669: Projected Textures for Starfall
As it currently stands, the only way to use projected textures alongside Starfall is to spawn a gmod or wiremod lamp, but this is very limiting compared to what is possible with direct Lua control over projected textures. These would be a useful and good addition, though they will need new particular permissions and cvars to not be abused since they can significantly affect framerate and cause crashes. I think they could fit into light.lua, but creating a new library for them shouldn't be off the table. Feedback and opinions appreciated

### PR DESCRIPTION
**Pull request by Advers**
Resolves #1669

### CODE REVIEW

**Comment by wrefgtzweve** [comment]
Having some kind of limit/performance tracker would be great, projected textures can absolutely rip fps

**Comment by thegrb93** [comment]
Yeah, SF.LimitObject should help

**Comment by thegrb93** [comment]
@Advers have you been able to test this?

**Comment by Advers** [comment]
Not yet. The last couple weeks were my university finals week so I had been pretty limited on my time. I'll look at it here soon.

**Comment by Advers** [comment]
https://github.com/user-attachments/assets/b0a1bd99-6768-4e85-8ff1-9bf51ac5099e

Appears to be fully functional. I've tried most of the functions and not gotten any errors, and the limit appears to be working.

**Pull request merged**
