### PR TITLE
Added permissions for Entity:getPos()

### PR DESCRIPTION
**Pull request by adamnejm**

### CODE REVIEW

**Comment by thegrb93** [comment]
I think we should avoid the permission check if the entity IsPlayer() or IsNPC()

**Comment by adamnejm** [comment]
Okay, I agree

**Comment by thegrb93** [comment]
Should be `if not ent:IsPlayer() and not ent:IsNPC() then`

**Comment by thegrb93** [comment]
Or `if not (ent:IsPlayer() or ent:IsNPC()) then`

**Comment by thegrb93** [comment]
https://en.wikipedia.org/wiki/De_Morgan%27s_laws

**Pull request merged**
