### PR TITLE
Add pcall/xpcall

### PR DESCRIPTION
**Pull request by edgarasf123**
Haven't tested this stuff yet

### CODE REVIEW

**Comment by thegrb93** [comment]
The point of xpcall is that the callstack is still intact in the callback so I think it's a bit pointless here.

**Comment by edgarasf123** [comment]
Its more for compatibility reasons, like with libraries and stuff

**Comment by thegrb93** [comment]
You can define it in your script. Not sure this its appropriate for the main code.

**Comment by edgarasf123** [comment]
Well, I think SF should implement as many original lua functions as possible.

**Comment by thegrb93** [comment]
Okay, we'll probably need to fix it later though.

**Pull request merged**
