### PR TITLE
Documented some libs

### PR DESCRIPTION
**Pull request by adamnejm**
Didn't put anything in `-- @class` on math.pi and math.huge, wire.ports is marked as a table, but I can't do the same with numbers, can I?
Not quite sure if to document `lookup_table` in table.copy, seems internal
Don't know how to document this https://wiki.facepunch.com/gmod/math.calcBSplineN please help
All functions with DEPRECATED warning on Gwiki also have this warning in SF Docs, but simplified
Untested, too lazy to open up gmod, but should work fine

### CODE REVIEW

**Comment by thegrb93** [comment]
I think math.pi and math.huge would be marked as --@field

**Comment by thegrb93** [comment]
Can merge this once docs are ready for it.

**Comment by Damianu** [comment]
Can you rebase and PR it onto test_doc?

**Comment by adamnejm** [comment]
I deleted my fork of sf containing libdocs branch so this is an orphan, don't think I can fix this pr
<sub><sup>Thanks for all the help, D! <sub><sup> /s </sup></sub></sup></sub>

**Pull request closed without merging**
