### PR TITLE
add screenshake function

### PR DESCRIPTION
**Pull request by LightRobin**
adds screenshake function, player needs to be connected to hud for it to work

### CODE REVIEW

**Comment by thegrb93** [comment]
A bit strange that the position and radius aren't used on client.

After https://github.com/thegrb93/StarfallEx/pull/1025 gets merged. This can be shared and the position+radius parameters can be used. I think those should be the last two input parameters so that nil isn't needed for when its used on client.

**Comment by thegrb93** [comment]
Something tells me that spamming this function in serverside might cause net overflow so maybe best to keep it clientside.

**Comment by thegrb93** [comment]
Would be cool to have serverside, but I don't think we can filter the players it affects. This should be fine.

**Comment by thegrb93** [comment]
Something tells me inf/nan inputs will cause the shaking to last forever. I think we need some number checks. Also checkluatype(var, TYPE_NUMBER)

**Comment by LightRobin** [comment]
mk, will do some testing and see

**Comment by LightRobin** [comment]
yep, it shakes forever, should really stop if you leave the hud i think

**Comment by thegrb93** [comment]
Maybe clamp the duration between 0 and 10.

**Comment by thegrb93** [comment]
Still need the checkluatypes and also need to make sure the other numbers aren't infinite too.

**Comment by LightRobin** [comment]
what does the checkluatypes do?, also tested it with both negative numbers and math.huge and it seemed fine

**Comment by thegrb93** [comment]
It checks that the input the player gave is a number.

**Comment by adamnejm** [comment]
How about just adding [cam.ApplyShake](https://wiki.facepunch.com/gmod/cam.ApplyShake) in addition or even instead of `util.ScreenShake`.
Didn't test how it works, but doesn't take the time parameter so it probably stop shortly after somebody leaves the HUD depending on the `factor`.

**Comment by thegrb93** [comment]
This function seems easier to use

**Pull request merged**
