### PR TITLE
Added a way of defining custom functions on types

### PR DESCRIPTION
**Pull request by Damianu**

### CODE REVIEW

**Comment by thegrb93** [comment]
This adds overhead though. I think https://github.com/thegrb93/StarfallEx/issues/528 would be a better solution.

**Comment by Damianu** [comment]
It does add overhead, I wouldn't expect it to be big tho (just additional lookup). Also it's quick implementation that can be replaced with #528 later on.

**Comment by thegrb93** [comment]
replacing it later would break backwards compatiblilty

**Comment by thegrb93** [comment]
Hm actually I guess you need a way to set the function actually so nvm.

**Comment by Damianu** [comment]
```return SF.instance.typeMethods[name][ind] or methods[ind]```
Could be better, but not sure if there arent any edge cases.

**Comment by Damianu** [comment]
As for breaking compatibility we can always leave the function and just change how it works internally.

**Comment by thegrb93** [comment]
`return SF.instance.typeMethods[name][ind] or methods[ind]` should be fine

**Pull request merged**
