### PR TITLE
Remove remnant return type from render.getScreenEntity documentation

### PR DESCRIPTION
**Pull request by adamnejm**
Fixes: #1922

### CODE REVIEW

**Comment by thegrb93** [comment]
Would it be worth adding support for huds? It might've actually worked before but just got broken by a change.

**Comment by adamnejm** [comment]
Well since now there's no specific component, it wouldn't make much sense I think.

I added this https://github.com/thegrb93/StarfallEx/pull/1595 instead not that long ago, since people were looking for a way to see it the HUD is active.

Underlying `renderEnt` is only used for screen entity now in the codebase.

**Comment by adamnejm** [comment]
I guess you could return the HUD component if it's present and the HUD is active? But honestly that would work better as a separate function

**Comment by thegrb93** [comment]
Huds don't invoke the rendering so nvm.

**Review by thegrb93 — APPROVED** [review]

**Pull request merged**
