### PR TITLE
Fix docs searchbar. Fixes #884

### LINKED ISSUE #884: Docs searchbar can't be accessed if window isn't wide enough

### PR DESCRIPTION
**Pull request by DaDamRival**

### CODE REVIEW

**Comment by Damianu** [comment]
Breaks scroll area which is much worse, fix pls

**Comment by DaDamRival** [comment]
I have come to the conclusion awesomium is way to painful to work with. If anyone else is interested here is [main.scss](https://gist.github.com/DaDamRival/436ae718e4042dc54ccb4a732548883d)

**Comment by thegrb93** [comment]
Can we set a minimum size on that panel? That should prevent the issue.

**Comment by thegrb93** [comment]
The css min-width property should do that.

**Comment by adamnejm** [comment]
I already have a fix
Pull requesting in 2 minutes

**Pull request closed without merging**
