### PR TITLE
WIP Add c-style comments

### PR DESCRIPTION
**Pull request by thegrb93**
Can't figure out block comments. Maybe someone else can look at it. @Damianu

Fixes: #514

### CODE REVIEW

**Comment by thegrb93** [comment]
The wire editor block comment works, except for multiline. As for Ace, I don't even know where to start.

**Comment by thegrb93** [comment]
Nice, just need to figure out why the wire multi-line comment only works for one line now.

**Comment by thegrb93** [comment]
I think this part needs to be changed as well. https://github.com/thegrb93/StarfallEx/blob/2e50fac19e43fd6c66f3250b8850370160f40d62/lua/starfall/editor/syntaxmodes/starfall.lua#L224

**Comment by CornerPin** [comment]
Done.

**Comment by Damianu** [comment]
You'd have to change blockcomment to work as a number/enum instead of boolean to know which type of comment it is.  Then just look at how --[[ is handled and ]] (the part you sent)

**Comment by CornerPin** [comment]
@thegrb93 dunno, the comment closing works for me
image

**Comment by thegrb93** [comment]
That should do it

**Pull request merged**
