### PR TITLE
New domain in whitelist.

### PR DESCRIPTION
**Pull request by kirkarr**
I'm added avatars.akamai.steamstatic.com domain into whitelist.  It's contains steam user avatars.

### CODE REVIEW

**Comment by ANormalTwig** [comment]
Bro, what the hell happened.

**Comment by adamnejm** [comment]
WTF

**Comment by ANormalTwig** [comment]
Oh, you're requesting changes to the wrong branch. You need to request a merge into the `master` branch.

**Comment by adamnejm** [comment]
Making PRs from the browser be like that

**Comment by kirkarr** [comment]
> Oh, you're requesting changes to the wrong branch. You need to request a merge into the `master` branch.

Sorry, i'm maked mistake. It's my first pull request.

**Comment by jamestrotter** [comment]
wouldn't be surprised if a platform as big as steam are using multiple CDNs - a single CDN usually doesn't give the best global coverage. It's not unusual for a platform to use both Akamai & Cloudflare

**Comment by thegrb93** [comment]
We should use a pattern instead then, yeah.

**Comment by thegrb93** [comment]
Those other steam urls might need to be updated too

**Pull request merged**
