### PR TITLE
Fixes #1215

### LINKED ISSUE #1215: ``prop.createSent`` creates broken E2s in certain cases
Was investigating a bug @Cheatoid encountered and found that since SF overrides the string library at runtime, E2's tokenizer is broken in https://github.com/wiremod/wire/blob/384809700d1cd250cf0f3f5b98d1e642e5131cd3/lua/entities/gmod_wire_expression2/base/tokenizer.lua#L91 (called by https://github.com/wiremod/wire/blob/384809700d1cd250cf0f3f5b98d1e642e5131cd3/lua/entities/gmod_wire_expression2/base/tokenizer.lua#L128)

This errors with "error in error handling" (thanks lua, very helpful), but really is just ``SF.Throw`` with "2 ext search length too long (500 max)" if you have a comma in the code it seems.

Could just push a change in wiremod to use string.find instead of ``(""):find()`` but this really pertains Starfall so I wanna know what you think @thegrb93

Another thing that is kinda gross is that the E2 acts as if it's been duped() and doesn't run with the first var set so first() never triggers which could be misleading

### PR DESCRIPTION
**Pull request by Cheatoid**
Fixes #1215 (for real)

### CODE REVIEW

**Comment by Cheatoid** [comment]
[Use this link for cleaner diff preview](https://github.com/thegrb93/StarfallEx/pull/1222/files?diff=unified&w=1)

**Comment by thegrb93** [comment]
This would've opened up a very obscure and serious security hole had I not implemented safe quota throwing in the past. Not a fan of messing with SF.runningOps .

**Comment by thegrb93** [comment]
Need to throw if the pcall returns false so this function doesn't error silently.

**Comment by Cheatoid** [comment]
> This would've opened up a very obscure and serious security hole had I not implemented safe quota throwing in the past. Not a fan of messing with SF.runningOps .

I understand, but there isn't any other way around this, unless you want to desugar all `string:` calls in E2 spawning code (tokenizer, parser, preprocessor, ...). Those external functions (code which I wrapped in `pcall`) were never intended to be called with string metatable patched, that's the main reason this issue exists as it results in obscure errors.
On the other hand, there should be nothing getting in the way here, because all of the code is run on a single/main thread, so this should be all good.

> Need to throw if the pcall returns false so this function doesn't error silently.

Ok I will fix that, but obviously have to make sure to restore runningOps, no matter what.

**Comment by thegrb93** [comment]
I'd honestly rather this be fixed in wire. Those functions would be faster if they didn't use __index anyway.

**Comment by Cheatoid** [comment]
> I'd honestly rather this be fixed in wire. Those functions would be faster if they didn't use __index anyway.

So, you're saying it is 3rd-party's problem that SF is patching string metatable? 😕

**Comment by thegrb93** [comment]
Just saying what I prefer. It's probably fine here. Anything using string __index should be fixed imo lol. I despise that garry added it

**Pull request merged**
