### PR TITLE
WIP Custom processor tool screen

### PR DESCRIPTION
**Pull request by adamnejm**
Work in progreess - don't merge.
Just putting it here to motivate myself a little

### CODE REVIEW

**Comment by thegrb93** [comment]
Looks cool. I'll check it out

**Comment by adamnejm** [comment]
It will most likely make test whole screen black if you launch your game on this branch, just saying...

**Comment by adamnejm** [comment]
Plan was to use the default scrolling-style screen, do some fun things like replace "Garry's Mod Hello" with StarfallEx_commitID add yours script name and realm
But here I have a little more control, added the particles can also add info about the chip instances you're looking add etc
If the falling stars are too gimmicky I can go back to the previous OR more simple concept but that's no fun :coffin:

**Comment by Neatro** [comment]
If the screen is a rendertarget, then the trails can be achieved by overlaying the rt with a black color with around 64-128 alpha and then drawing everything again the next frame, causing a fade effect of the last frame, this does mean to not clear the frame before drawing at all

**Comment by thegrb93** [comment]
I kind of want them to rotate as well, so might be better just to do sprites for them all.

**Comment by thegrb93** [comment]
Moving the commit @Damianu made

**Comment by thegrb93** [comment]
test

**Comment by thegrb93** [comment]
test

**Comment by thegrb93** [comment]
test

**Comment by thegrb93** [comment]
I'll work on getting this done next after the render bugs.

**Pull request closed without merging**
