### PR TITLE
Multi-segment 3D beam functions

### PR DESCRIPTION
**Pull request by Advers**
Adds functions to use gmod's multi-segment 3D beam functions in Starfall

### CODE REVIEW

**Comment by thegrb93** [comment]
Doesn't this crash the game or cause bad stuff if used incorrectly?

**Comment by Advers** [comment]
I tried using it incorrectly on purpose, but nothing happens for me at all, except if render.end3DBeam is skipped -- then the beam isn't drawn. No errors or crashes. Can you describe what causes a crash?

**Comment by thegrb93** [comment]
I'll have to try it

**Comment by thegrb93** [comment]
It definitely used to, but I think gmod devs fixed it

**Review by thegrb93 — APPROVED** [review]

**Pull request merged**
