### PR TITLE
Disable anything by default that could expose your IP.

### PR DESCRIPTION
**Pull request by TheFreezebug**
let me get out of your way gordon
and then mossman died because why not

(people keep complaining about this)

### CODE REVIEW

**Comment by thegrb93** [comment]
I don't like limiting these features, nor would anyone who has to explain 1000x a day how to enable them to everyone they want to share their creation with.

**Comment by adosikas** [comment]
To add to this:  
The main problem with clientside http isn't exposing IP's (which isn't that bad).

The problem is that it allows players to make other players (who may not even be aware of starfall, and just joined the server) make requests to any URL, which not only includes ip loggers, honeypots or worse.

At least there should be a whitelist with some "good" hosts that adress illegal content, so imgur, dropbox, etc.

To give a comparison: Steam doesn't auto-open links you get sent by strangers (and if it did you'd bet they would not enable it by default). What starfall does is basicly that.

**Comment by thegrb93** [comment]
Any website can make you request any url without your knowledge.

**Comment by thegrb93** [comment]
Any app on your phone/computer can make a request to any url without your knowledge.

**Comment by thegrb93** [comment]
Get over it.

**Comment by adosikas** [comment]
Any website yes, but not random other users of the same website, which is where my problem is.

**Comment by thegrb93** [comment]
Note: starfall does print requests in console.

**Pull request closed without merging**
