### PR TITLE
Send starfall code to client once and only when fully initialized

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #845

### CODE REVIEW

**Comment by thegrb93** [comment]
@ShadowzOfTheDark can you see if this works better?

**Comment by thegrb93** [comment]
Seems to work fine so far. Just have to make sure it works in multiplayer.

**Comment by adamnejm** [comment]
Will try to test on my server later in the day too

**Comment by adamnejm** [comment]
Everything seems to work pretty smoothly.
Testing conditions:
- shared & client-only scripts
- 2 sets of chips
1st in PVS that player spawns in
2nd in PVS that is closed off and not initiated on join (map ents non-existent on client)
- scripts used multiple different libraries together, including: render, mesh, holograms
- small & quite large scripts (ye very accurate ikr)
- windows & linux
- pvs rape on join (aka moving player quickly between different PVS while joining)

None of the scripts errored, every single one loaded, even those in closed off PVS seem to be running once player got into the area for the first time.

**Comment by adamnejm** [comment]
If code is done, then I'm positive you can merge

**Pull request merged**
