### PR TITLE
Remove websocket (its deprecated)

### PR DESCRIPTION
**Pull request by Be1zebub**
Unfortunately Rub*t broke it :(

### CODE REVIEW

**Comment by ANormalTwig** [comment]
Still usable with [GModCEFCodecFix](https://github.com/solsticegamestudios/GModCEFCodecFix).

**Comment by Vurv78** [comment]
What? Why?

Give literally any proof that this has happened.
Either way this would still be useful in case of using GmodCEFCodecFix

**Comment by Be1zebub** [comment]
> Give literally any proof that this has happened.
you can try yourself `var socket = new WebSocket("ws://te.st");`
> Either way this would still be useful in case of using GmodCEFCodecFix, and could be ported to also work using https://github.com/FredyH/GWSockets, which it is based off of.
okey, then gwsocket support need to be implemented (or there is should be hint about what is supported only with GmodCEFCodecFix)

**Comment by Vurv78** [comment]
> you can try yourself var socket = new WebSocket("ws://te.st");

This is not proof. You said rubat broke it, where did he say that? Any commits to the internal garrymod repo?
A lot of people have reported it being broken but it's mostly inconsistent.

**Comment by Be1zebub** [comment]
it not listed in commits or update notes, at least I couldnt find it.
websockets was quietly disabled about a 1.5 years ago.

**Comment by UnrealEugene** [comment]
By the same logic we should remove luasocket library since gmod doesn't support it.
/s

**Comment by Be1zebub** [comment]
> gmod doesn't support it. 
 
thats why this line exists https://github.com/thegrb93/StarfallEx/blob/c07a2123439a62c0bd32b471ae2eb7c91ccf3d80/lua/starfall/libs_cl/socket.lua#LL1C8-L1C18

**Comment by UnrealEugene** [comment]
> > gmod doesn't support it.
> 
> thats why this line exists https://github.com/thegrb93/StarfallEx/blob/c07a2123439a62c0bd32b471ae2eb7c91ccf3d80/lua/starfall/libs_cl/socket.lua#LL1C8-L1C18

So we conclude that there is no reason to completely delete websocket library. Adding similar logic to `websocket.lua` or even just modifying the docs for Websocket is enough to solve the issue.

**Comment by ANormalTwig** [comment]
Just add the fact that you might need to use GModCEFCodecFix to the docs instead of getting rid of it.

**Pull request closed without merging**
