### PR TITLE
Add http.base64Decode

### PR DESCRIPTION
**Pull request by CornerPin**
https://github.com/thegrb93/StarfallEx/issues/724.
Tried to optimize it as much as I could.

### CODE REVIEW

**Comment by thegrb93** [comment]
Did you encode and decode some stuff to test fidelity yet?

**Comment by CornerPin** [comment]
Yeah, it works fine except it cannot process newlines that `util.Base64Encode` puts every 72 characters, so they have to be replaced using `gsub` before calling `http.base64Decode`.

**Comment by thegrb93** [comment]
Oh, that's strange. Is there anyway to make this noop newlines? Probably be faster than gsub.

**Comment by CornerPin** [comment]
It seems like `gsub` is the fastest way. Alternatively, we can remove newlines from `http.base64Encode` or make them optional.

**Comment by CornerPin** [comment]
For some reason when the function is called from a Starfall script, it performs much slower.
SF:
```
1931699 bytes to encode
2575600 bytes to decode
Encoding: 0.0075629999992088
Decoding: 0.31249190000017
Ratio: 41.31851117716
```
Just Lua:
```
1931699 bytes to encode
2575600 bytes to decode
Encoding: 0.0076470999993035
Decoding: 0.055720600001223
Ratio: 7.2865007658195
```
Is there something that can be done with that?

**Comment by Damianu** [comment]
That's overhead of measuring cpu time. I dont think you can easily fix it

**Comment by thegrb93** [comment]
Could increase the debug hook's steps to reduce the frequency of measurement.

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/instance.lua#L168

**Comment by thegrb93** [comment]
Since this was added, https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/instance.lua#L175 , it's probably safe to increase it quite a bit.

**Comment by CornerPin** [comment]
Just tried it and there's no difference at all, no matter how large the step is.

**Comment by thegrb93** [comment]
Nice

**Pull request merged**
