### PR TITLE
fix math.slerpQuaternion

### PR DESCRIPTION
**Pull request by yingKatsu**
current version doesnt work. can we steal the one from e2 instead? idk how quat math works.

# Before creating pull request
- Move all changes to **separate** branch (Don't use master of your fork).
- **Don't** reuse branches.
- **Don't** sync that branch after creating pull request unless it's really needed. (IE. upstream changed code structure).
- Test it and try fixing bugs ahead.
- If you know about any bugs, make sure to list them in PR message.
- Make sure pull request message informs about **ALL** the changes.
- Your pull request can be work-in-progress if you want others to help you with coding or give you  opinions, just make sure to state it's not ready.
- Try to avoid messing with whitespaces. (Setup your editor properly to follow our style).
- If you find whitespaces that don't follow our style you can fix them in separate commit.
- Read about [github flow](https://guides.github.com/introduction/flow/)
​

# Thank you

Thank you for contributing and helping StarfallEx community!

### CODE REVIEW

**Comment by Advers** [comment]
yes please

**Comment by thegrb93** [comment]
The original code looks correct, although maybe the quatConj(out) is wrong and shouldn't be there. It's following this formula:

**Comment by thegrb93** [comment]
Could also be the exponentiation is implemented incorrectly but I'll need to test.

**Comment by thegrb93** [comment]
It seems to be working fine?

```lua
--@name Untitled
--@author Sparky
--@server

Q1 = Angle(0,0,0):getQuaternion()
Q2 = Angle(80,140,40):getQuaternion()

local h1 = hologram.create(chip():getPos()+Vector(-100,0,50), Q1:getEulerAngle(), "models/props_c17/furnitureStove001a.mdl")
local h2 = hologram.create(chip():getPos()+Vector(0,0,50), Q1:getEulerAngle(), "models/props_c17/furnitureStove001a.mdl")
local h3 = hologram.create(chip():getPos()+Vector(100,0,50), Q2:getEulerAngle(), "models/props_c17/furnitureStove001a.mdl")

hook.add("think","",function()
    h2:setAngles(math.slerpQuaternion(Q1,Q2,math.sin(timer.curtime()*5)*0.5+0.5):getEulerAngle())
end)
```

[2024-10-15 06-49-47.webm](https://github.com/user-attachments/assets/691c8db1-d469-4894-a653-a5788637dbab)

**Comment by thegrb93** [comment]
Yeah, I was right, the quatConj is wrong. Just need to delete that.

**Review by thegrb93 — APPROVED** [review]

**Comment by thegrb93** [comment]
[2024-10-15 06-54-03.webm](https://github.com/user-attachments/assets/88173a07-a15d-49e1-bd7f-819e7bb66ba7)

**Pull request merged**
