### PR TITLE
Add render.capture()

### PR DESCRIPTION
**Pull request by ANormalTwig**
Add render.capture() for saving rendertargets to a png or jpeg.

### CODE REVIEW

**Comment by thegrb93** [comment]
Looks like a pretty cool function. Can you rename it to render.captureImage?

**Comment by Vurv78** [comment]
Missing docstring for the return value

**Comment by thegrb93** [comment]
Pull and test those changes and if it works then I'll merge

**Comment by ANormalTwig** [comment]
image
image
works

**Comment by thegrb93** [comment]
Cool thx

**Pull request merged**
