### PR TITLE
Add Hologram:setCullMode()

### PR DESCRIPTION
**Pull request by Advers**
Adds a function that allows for the cull direction of holograms to be changed without forcing the user to create a render hook

### CODE REVIEW

**Comment by thegrb93** [comment]
I think cullmode can be controlled via the material right? Are you able to use a material instead?

**Comment by Advers** [comment]
You want to clone each hologram's material to set the "inverted" flag? I think that feels like a lot more work and memory use for the purpose. Do you have a specific reason for wanting to do it this way?

**Comment by thegrb93** [comment]
This adds passive render overhead to hologram

**Comment by thegrb93** [comment]
My only other complaint is that cullmode has 3 modes and your bool only allows support for 2 modes.

**Comment by thegrb93** [comment]
Huh, I swear there used to be a 'none' cullmode which would make the faces draw on both sides.

**Comment by thegrb93** [comment]
I guess I was just thinking of the nocull material flag

**Review by thegrb93 — APPROVED** [review]

**Pull request merged**
