### PR TITLE
Add particle system library

### PR DESCRIPTION
**Pull request by TheFreezebug**
implement particle system library

### CODE REVIEW

**Comment by TheFreezebug** [comment]
may end up changing the reference type

**Comment by TheFreezebug** [comment]
might need to wait for CPPI

**Comment by nickthegamer5** [comment]
Any new progress on this?

**Comment by thegrb93** [comment]
Prop protection must be implemented first

**Comment by Damianu** [comment]
I think that before prop protection getting a fix we should have permissions themselves fixed. Right now in some cases permissions cant access instance.

**Comment by thegrb93** [comment]
Yeah I'll refactor and optimize permissions too.

**Pull request merged**
