### PR TITLE
Add socket library

### PR DESCRIPTION
**Pull request by thegrb93**
```lua
--@name
--@author
--@client

local sock = socket.connect4("sparkysandbox.org", 80)
sock:send("GET / HTTP/1.0\r\nHost: sparkysandbox.org\r\n\r\n")
for v in function() return sock:receive() end do
    print(v)
end
```

### CODE REVIEW

**Comment by thegrb93** [comment]
My only concern is this may allow malicious network access by server lua code on clients using this module.

**Comment by thegrb93** [comment]
https://github.com/danielga/gmod_luasocket/issues/7

**Comment by h3xcat** [comment]
You might be able to implement websocket through chromium, without requiring external binary libraries. Also it would eliminate the security concern.

**Comment by thegrb93** [comment]
Sockets now have whitelist implemented. Instructions are in the library doc

**Pull request merged**
