### PR TITLE
Fix superuser steamid calls

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #1654

### CODE REVIEW

**Comment by Advers** [comment]
It does appear to work fine now, but this has led me to discover another separate issue also caused by --@superuser. Prints on both server and client are not shown to the user

**Comment by thegrb93** [comment]
Superuser chips don't have an owner so that is expected

**Comment by Advers** [comment]
Expected, yes, but it's not exactly very practical. This PR can probably safely be closed though, and an issue post or PR about the prints can be made separate

**Comment by thegrb93** [comment]
@Advers getting the prints to work clientside should be easy. Though important to note that it would print on any client its ran on.

**Comment by thegrb93** [comment]
Getting it to work for serverside would require a new var on the instance for the superuser owner probably.

**Pull request merged**
