### PR TITLE
entity:getAngleVelocity() now returns an angle

### PR DESCRIPTION
**Pull request by szymski**
Works exactly like E2's angVel().

### CODE REVIEW

**Comment by thegrb93** [comment]
I just found that this will actually break almost all my chips. Here's the code I use.

TireBL:applyTorque(-TorqueL - TireBL:getAngleVelocity()*3)

So the getAngleVelocity is used for torque.

Maybe instead, you could create a new function that returns an angle, like getAngleVelocityAngle?

**Comment by thegrb93** [comment]
SF's getAngleVelocity() is E2's angVelVector()

**Comment by szymski** [comment]
Done

**Comment by thegrb93** [comment]
Cool. Now if only team garry would wrap the source engine applytorque function so we don't need lua to do so many calculations to apply rotational force on an entity.

**Pull request merged**
