### PR TITLE
Fix coding style

### LINKED ISSUE #99: Find something that can cure the whitespace plague.

### PR DESCRIPTION
**Pull request by its-suun**
Changes:
* remove whitespaces before parameters
* remove whitespacess between `( )`
* remove whitespaces between `[ ]`
* add spaces between `{ }`
* add spaces after `,`
* add spaces around `+`, `=`, `*`, `/`
* `!=` -> `~=`, `!` -> `not`, `&&` -> `and`, `||` -> `or`

I ran every file through `luac` and only errors are about `continue` so syntax should be fine.

Fixes #99

### CODE REVIEW

**Comment by ZpyduCat** [comment]
ti eblan?

**Comment by Benjiko99** [comment]
I would not merge this.
I'll make a better Pull Request.

**Comment by thegrb93** [comment]
Looks really good for the most part, but I noticed that it sometimes removes spaces after commas in function arguements and it butchers if statements or for/while loops with parentheses in them.

**Comment by thegrb93** [comment]
Actually the commas appear to be fine. Just need to fix the whitespaces in if statements and loops that contain parentheses. If that can be fixed, it'd be good to merge.

**Comment by its-suun** [comment]
Well great now it has conflicts cause of the c style operators pull request which i changed anyway

**Comment by thegrb93** [comment]
Can the PR be recreated?

**Comment by its-suun** [comment]
Should be right now, i removed the removing of spaces before parentheses tho since i can't get it right with the tools i use

**Pull request merged**
