### PR TITLE
Add PostDraw2DSkyBox hook

### PR DESCRIPTION
**Pull request by Hazeofdream**
https://wiki.facepunch.com/gmod/GM:PostDraw2DSkyBox

### CODE REVIEW

**Comment by thegrb93** [comment]
Look in render.lua for where the render hooks are to add it.

**Comment by Hazeofdream** [comment]
like this?

**Comment by ANormalTwig** [comment]
the second argument is the name of the hook when used in starfall, you can leave it at `nil` if you just want it to use the original hook name

**Comment by thegrb93** [comment]
Can you put it next to the other 'PostDrawSkyBox' hook and also undo the change in the other file?

**Comment by Hazeofdream** [comment]
accidently committed to my master fork lets go

**Comment by thegrb93** [comment]
I meant delete the changes in hook.lua. It only needs to be in render.lua.

**Pull request merged**
