### PR TITLE
Add input.lockControls

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #666
Fixes: #494

### CODE REVIEW

**Comment by thegrb93** [comment]
See if this works, @zxvnm4

**Comment by zxvnm4** [comment]
I'll go and test it, I see from the commits that you've added what I described earlier. This is... very useful thanks.

**Comment by zxvnm4** [comment]
I tested what you added it appears to function properly. There isn't too much code added, it's fairly bulletproof with the alt key disabling it. If I were to be super picky I could say that you should also consider edge cases where the screen ent is deleted. I suppose the edge case for the hud where it's entity is deleted it also disables such?

KeyPress hook doesn't pick up the client keys but inputPressed does, although that seems fair.

I mentioned that uh, I wanted a function to disable and enable the screen's ability to be a keyboard. I don't know if you disagreed with that or that you misunderstood it. If you did misunderstand it I sort of meant like a library function to disable it and enable a screens ability to be a keyboard. Although having the checkbox option works, just having it as it is makes user experience with the screen a little clunky, potentially.

If you're interested in what I'm working on, it's.. it's just a fairly efficient, complicated(?), GUI library in starfall. It functions properly for my current implementation of it. I've made a music player to test it and I got a dedicated server running with all of this on it.

**Comment by thegrb93** [comment]
Yea a library function would be better. I'll do that

**Comment by zxvnm4** [comment]
Oh, and I should note about inputPressed, that hook does allow the chip to pick up on button presses even when you are in the exit screen, but if you make it toggleable then I can use KeyPress during normal operations and then use inputPressed when the user is typing. Although that might be still problematic. As well, now that I think of it, you should also have a function to check to see if the player is currently using the keyboard or not. Even if you can toggle it, it might be useful.

**Comment by thegrb93** [comment]
There. Hopefully that works.

**Comment by zxvnm4** [comment]
Thanks, that looks perfect, I'll go and put the changes it into my code to check it out.

**Comment by zxvnm4** [comment]
Took me awhile start implementing it in my code but, as expected from reading what you've added, everything works great. I think I'm finally pleased, I'll close that issue post.

**Comment by zxvnm4** [comment]
This might be a little more code, sorry for this, you don't need to add it; but I've just realized that having the code be able to also boot the player out of the lock controls, for the screen, would also make things more intuitive for the user, in my specific use case. 
(I got a text box, you 'use' it to start typing and then you can click out of it to stop typing, or hit alt in this case, so far it works fine but I can't click out of it to stop typing I have to hit 'alt')
You could just make that if you use setComponentLocksControls() to disable a components ability to act as a keyboard, you also make it delock controls for the players that are currently locked using it.

**Pull request merged**
