### PR TITLE
Add a few game events as hooks.

### PR DESCRIPTION
**Pull request by ANormalTwig**
Closes: #1191

### CODE REVIEW

**Comment by thegrb93** [comment]
Looks good.

One improvement is if you can replace all the 'id' vars with instance.WrapObject(Entity(id)). Also if you can put them into the table directly instead of as locals first, that'd be better too.

**Comment by ANormalTwig** [comment]
Not sure about the 'id' vars since they are always userids except for player_hurt's attacker which can be 0 if there was no attacking player.

**Comment by ANormalTwig** [comment]
> Looks good.
> 
> One improvement is if you can replace all the 'id' vars with instance.WrapObject(Entity(id)). Also if you can put them into the table directly instead of as locals first, that'd be better too.



will instance.WrapObject have any problems if it tries to wrap a null entity?

**Comment by thegrb93** [comment]
It shouldn't

**Comment by ANormalTwig** [comment]
actually I just realized that the player entities arn't valid when player_connect is called

**Comment by thegrb93** [comment]
A few more things:
Make the player arg first and the bot arg last in the player_ hooks.

Also you can provide a second argument to the `add` function to give the hook a better name for starfall. Would be good to give the hooks names without the `_`. Don't forget to update the docs with these changes.

**Comment by thegrb93** [comment]
Also it would be good to verify which of these are server-only/shared/client-only

**Comment by ANormalTwig** [comment]
From testing I was able to get them to run on both server and client but it might be different for players who aren't hosting the server.

**Comment by thegrb93** [comment]
All right that sounds good.

Last changes, the hooknames don't need 'event' at the end of them and in player_hurt, you could move data.health to be the last arg.

**Comment by ANormalTwig** [comment]
What should player_hurt be named since PlayerHurt is already a hook name

**Comment by thegrb93** [comment]
Looks like the current PlayerHurt is server only, so this one can be the client-only PlayerHurt

**Comment by ANormalTwig** [comment]
doesn't look like I can make a serverside PlayerHurt and a clientside PlayerHurt without one overriding the other in the docs

**Comment by thegrb93** [comment]
All looks good. Thanks

**Pull request merged**
