### PR TITLE
Added net.writeData and net.readData

### PR DESCRIPTION
**Pull request by McDunkinY**

### CODE REVIEW

**Comment by thegrb93** [comment]
I'm currently redoing the net library as there are a lot of issues. writeData will be included in it.

**Comment by McDunkinY** [comment]
Can you add while you work on it? I need to to be able to network compressed data.

**Comment by thegrb93** [comment]
Almost done, just give me a few minutes.

**Comment by thegrb93** [comment]
If I merge this now then I'll have to deal with git conflicts and shit.

**Comment by thegrb93** [comment]
Okay I pushed the update. It's not fully tested. Please let me know if anything's not working.

**Pull request closed without merging**
