### PR TITLE
friction and elasticity functions

### PR DESCRIPTION
**Pull request by LightRobin**

### CODE REVIEW

**Comment by thegrb93** [comment]
It looks like getElasticity should be shared too, but I think I'd prefer them both server only unless there's some case you'd need it clientside.

**Comment by LightRobin** [comment]
Ah I didn't notice get elasticity was shared too, having it shared could be useful if you had a chip that was fully clientside and needed it, would save you needing to network, up to you tho, I'll change it tomorrow, heading to bed rn

**Comment by thegrb93** [comment]
> Ah I didn't notice get elasticity was shared too, having it shared could be useful if you had a chip that was fully clientside and needed it, would save you needing to network, up to you tho, I'll change it tomorrow, heading to bed rn

setting something clientside typically doesn't network it, it just overrides the server value.

**Comment by LightRobin** [comment]
i meant that in the context that you are writing a sf chip that runs on @client and need to access it for soem reason, if the functions was only SV then youd have to use net messges within sf to access the elasticity

**Comment by thegrb93** [comment]
See if it even works in CL first.

I think the last thing this needs is permission checks to ensure players can only modify their own things. entities.CanTool permission should be fine (this is server only, might need to make it shared; i can help with this if we decide to go this route).

**Comment by LightRobin** [comment]
just tested, seems that getElasticity does work on client but setting it doesnt

**Comment by thegrb93** [comment]
Make sure to define the `ent` in your permission checks

**Comment by LightRobin** [comment]
rip, rookie error

**Comment by LightRobin** [comment]
hmm, its erroring, addons/starfall/lua/starfall/permissions/core.lua:69: attempt to call a nil value

**Comment by thegrb93** [comment]
my bad, should be `entities.canTool`

**Comment by LightRobin** [comment]
seems to be good now

**Comment by thegrb93** [comment]
Looks good. Thanks!

**Pull request merged**
