### PR TITLE
Made net.writeBit take number and added net.writeBool and net.readBool

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by thegrb93** [comment]
Just replace-all writeBit, readBit to writeBool readBool

**Comment by DaDamRival** [comment]
readBit used to return a 0 or 1 tho, so would need to replace more. But i guess that's fine since i'm used by now to replace functions that had no reason to be changed / removed.

**Comment by adamnejm** [comment]
I still can't stand how holoClip was moved to clientside

**Comment by thegrb93** [comment]
No, readBit returned bool.

**Comment by thegrb93** [comment]
Ah in that case you need to update writeBit yea

**Pull request merged**
