### PR TITLE
Hud can now popup permission overwrite menu

### PR DESCRIPTION
**Pull request by DaDamRival**
Hud will now be able to popup permission overwrite menu when pressed use on same as with chip and screen.

### CODE REVIEW

**Comment by thegrb93** [comment]
Wouldn't it get annoying to have the permission menu pop up everyone you wanted to toggle a hud? Maybe a better solution is to have the context menu option appear for component entities as well.

I also don't like `if not x then return end` inside of entity hook functions since they usually get in the way of future code; just avoiding it the first time prevents it from needing to be changed later.

**Comment by DaDamRival** [comment]
While the context menu option for component entities is a good solution as well. I feel like the popup wouldn't cause any harm since it only popups when you haven't accepted it and most code that requests for permissions wouldn't work without them.

**Comment by Damianu** [comment]
Won't it also popup when you try to disconnect?

**Comment by DaDamRival** [comment]
If you didn't accept the permissions, yes

**Comment by thegrb93** [comment]
Sounds fine to me then

**Pull request merged**
