### PR TITLE
Added getent() to bit.lua

### LINKED ISSUE #1238: getent() missing from bit.lua

### PR DESCRIPTION
**Pull request by Jacbo1**
Resolves #1238

### CODE REVIEW

**Comment by thegrb93** [comment]
Something tells me this is going to break stuff because ss_methods is used across instances.

**Comment by thegrb93** [comment]
Let me check again

**Comment by thegrb93** [comment]
Yeah, this function will need to be assigned to the object in `bit_library.stringstream` since ss_methods is used by all instances. That or move everything into the `return function(instance)`

**Comment by thegrb93** [comment]
Same goes for readEntity

**Comment by thegrb93** [comment]
Added the fix. If you can test/finish then it should be good.

**Comment by Jacbo1** [comment]
Looks like it works

**Pull request merged**
