### PR TITLE
Fix-fixes net bursting & Color memory-leaks/performance

### PR DESCRIPTION
**Pull request by ThatOneCheetah**
I have implemented the `burst_tick` function, which basically does the same as was done in `net_library.start`.  
  
The difference is that it is called before every operation requiring the `burst` value to be updated; therefor I have moved the exception throwing for too large net packets to `net_library.send`, as no net_library-network traffic *should* occur before that.  
  
To be able to do this I added a `size` value which stores the size of the current net message, this is incremented in the local `write( ...` function and set to `0` in `net_library.start`.  
  
I have also permitted *8 bytes of overhead*, as we are dealing with floating-point calculations, and 8 bytes of overhead is perfectly reasonable.  
  
This might be considered a dirty fix, but it seems to work, for the time being.

### CODE REVIEW

**Comment by thegrb93** [comment]
getBytesLeft isn't accurate anymore since burst isn't subtracted until the send.

**Comment by ThatOneCheetah** [comment]
Having to use getBytesLeft inside of a netmessage makes sending packets with a static size a really big hassle. For example; I am doing `net.getBytesLeft()` outside of a netmessage to see whether I can send a package that I know could be 1024 bytes in size by doing `if net.getBytesLeft() < 1024 the return end`, however, because the burst isn't updated anywhere but when `net.Start()` is called this will just hang the hook at that point; and assuming you cannot abort a netmessage there is not really a way of telling what the burst value is at or how many bytes you can send at this very moment outside of one.  
  
To address the issue you named you can replace what `getBytesLeft` currently returns with: `return instance.data.net.burst - instance.data.net.size` I've forgotten to "support" checking inside of a net message as that is not how my code worked which seems to have caused the issue.

**Comment by thegrb93** [comment]
I see, so the problem is getBytesLeft is currently inaccurate since burst isn't updated until net.start. Go ahead and fix your getBytesLeft and I'll merge.

**Comment by thegrb93** [comment]
Also the byte overhead is unnessesary because epsilon at this range is about 9.0949470177293e-013

**Comment by ThatOneCheetah** [comment]
I'll fix it later today as it's currently 03:55am where I'm at.
About the byte overhead; I wasn't quite sure what was causing the burst to have ~3-4 inaccuracy at times without a clear reason as to why, so I decided too quickly that it must've been calculation inaccuracy, which it's not, I think it might have something to do with `CurTime()` and how it behaves if the client lags.

**Comment by ThatOneCheetah** [comment]
I have found the cause of the "inaccuracy", the name of the netmessage is included in the size of the netmessage itself, which of course is reasonable, but keeping the overhead is nice anyway, because as said, `CurTime()` doesn't always know how to behave.

**Comment by edgarasf123** [comment]
Yeah, net.getBytesLeft should work before net.start.


This is a hack I used to send big data in chunks for my [MIDI player](https://drive.google.com/open?id=0B11uwRQw_I-kN243ME5wd2o5bG8). Basically I use it to send files owner->server->players, because HTTP is not turned on by default, not even on server... It's bit offtopic, but why the hell is the server HTTP is off by default? I mean even E2 allows http...

**Comment by thegrb93** [comment]
Do all of the other libraries that rely on color still work? Entity, hologram, etc. I'll also test real quick.

**Comment by ThatOneCheetah** [comment]
> Do all of the other libraries that rely on color still work? Entity, hologram, etc. I'll also test real quick. Btw keep whitespace changes in another pr, they're so annoying to scroll through while trying to review code.
  
From what I can tell anything that accepts a `Color` type will also accept a table that is of the format `{r, g, b, a}` with numerical indexes.  
  
About the whitespace-changes thing: How do I do this? Is it something I must change in my text editor or git settings? *(I use SourceTree on Windows)*

**Comment by thegrb93** [comment]
Nvm, I found out how to git diff without showing whitespace changes. I'm testing this now.

**Comment by ThatOneCheetah** [comment]
I just noticed a slight error in my code which breaks `colorToHSV`, the function should be 
```
local h, s, v = ColorToHSV( unwrap( self ) )
return wrap( { h, s, v, 255 } )
```
instead.  

I cannot change this at the moment (on iPad, should really get to sleep).

**Comment by thegrb93** [comment]
No problems. I can correct that.

**Pull request merged**
