### PR TITLE
Move all the DLL in their dedicated folder

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Thank you for contributing and helping StarfallEx community!

### CODE REVIEW

**Comment by thegrb93** [comment]
They aren't in lua/bin to start with because they are optional modules. The user is expected to install them if they want them.

**Comment by adamnejm** [comment]
They could be moved to *modules* folder tho, it would make the main folder less cluttered

**Comment by dvdvideo1234** [comment]
Kinda, confusing to install in `dll` point of view, but, oh well.

**Comment by thegrb93** [comment]
@adamnejm I though of that too, but I want them to be visible so people know they exist.

**Comment by dvdvideo1234** [comment]
@thegrb93 Or write the readme it supports [modules](https://www.google.com/) :+1:

**Pull request closed without merging**
