### PR TITLE
VGUI Library

### PR DESCRIPTION
**Pull request by ZH-Hristov**
WIP VGUI Library
To-do:

- Permissions
- Add missing VGUI elements
- Burst Object + Limit (maybe idk)

### CODE REVIEW

**Comment by szymski** [comment]
Looks very promising. Do you plan on making it possible to draw VGUI panels on Starfall screens? I still should have codes for that somewhere and might help a bit if needed 🙃

**Comment by ZH-Hristov** [comment]
> Looks very promising. Do you plan on making it possible to draw VGUI panels on Starfall screens? I still should have codes for that somewhere and might help a bit if needed 🙃

Should be as simple as adding the SetPaintManually and PaintManual functions for the Panel type so yeah.

**Comment by szymski** [comment]
> Should be as simple as adding the SetPaintManually and PaintManual functions for the Panel type so yeah.
Haven't done it for a long time, but if I recall correctly, so easy it only seemed. There's a bunch of other stuff you need to take care of, in case SF isn't already taking care of them (can't really tell what that was atm), but if you had any difficulties - just let me know, I have a working prototype buried somewhere deep in my old addon directories, similarly for 3d2d cams ;)

**Comment by ZH-Hristov** [comment]
> > Should be as simple as adding the SetPaintManually and PaintManual functions for the Panel type so yeah.
> > Haven't done it for a long time, but if I recall correctly, so easy it only seemed. There's a bunch of other stuff you need to take care of, in case SF isn't already taking care of them (can't really tell what that was atm), but if you had any difficulties - just let me know, I have a working prototype buried somewhere deep in my old addon directories, similarly for 3d2d cams ;)

It seems to work fine, cept that it spawned in the air facing down for some reason, but that may be just me badly translating the GLua code to SF.
paintmanual
Code used:

> --@name
--@author
--@client

enableHud(player(), true)
local frame = vgui.createDFrame()
frame:setTitle( "PaintManual Test" )
frame:setSize( 500, 500 )
frame:setPaintedManually( true )

local m = Matrix()
m.type = "3D"
hook.add( "PostDrawTranslucentRenderables", "PaintManual Test", function()
	if frame then
		local eyePos = eyePos()
		local forward = entity(1):getForward()
		local forwardAngle = forward:getAngle()

    m:setAngles(Angle(0, forwardAngle.y - 90, forwardAngle.r + 90))
    m:setTranslation(eyePos + (forward * 250), Angle(0, forwardAngle.y - 90))
    m:setScale(Vector(0.2, -0.2, 1))

    render.pushViewMatrix(m)
			   frame:paintManual()
    		render.popViewMatrix()
	end
end )

**Comment by ZH-Hristov** [comment]
> Cool to see some of it working! I suppose tho, you haven't taken any steps yet to make it possible for panels painted in such way to receive user input, mouse and keyboard as well. That's what I mainly meant when saying it requires extra effort. It would be cool to have support for mouse and keyboard input, for example when using DTextEntry on a screen or in 3d2d context. Looking forward to having this lib officially in Starfall btw! Good job :)

Yeah, I haven't done anything about that.

**Comment by ZH-Hristov** [comment]
i hate github so bad
will reopen new one when sufficient progress is made

**Pull request closed without merging**
