### PR TITLE
Add debug.traceback and debug library. Fixes: #1150

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by x4fx77x4f** [comment]
Don't forget the aliases for the original `debugGetInfo` and `debugGetLocal`, for backwards compatibility.

**Comment by thegrb93** [comment]
Can't they just update them?

**Comment by x4fx77x4f** [comment]
Well, in this issue you seemed to care about backwards compatibility: https://github.com/thegrb93/StarfallEx/issues/1071

> I don't think anyone minds, but I would prefer this function in the bit lib but **it's not worth breaking things**.

> I guess an undocumented alias would be fine.

**Comment by thegrb93** [comment]
I think these functions are a lot less popular

**Comment by x4fx77x4f** [comment]
Here are some cases where I could find them being used.
[DebugTraceback.lua](https://github.com/Vurv78/lua/blob/bbecacc65715b7c4ab8bfd81cf3cdd08ee82e902/StarfallEx/Libraries/DebugTraceback.lua#L10)
[CSharp.glua](https://github.com/dnGLua/CSharp.glua/blob/ea05c486400aa35950415a07513ec24a78636bd6/CSharp.glua.Compiler/CoreSystem/StarfallCompat.lua#L7)
[gui2_docs.lua](https://github.com/DaDamRival/starfall_scripts/blob/4fbaf190ee18d96fee1b7da498560cf50ec4c1a4/example/gui2_docs.lua#L173)
[gameboy-emulator](https://github.com/bonnetn/gameboy-emulator/blob/b3e867327484ef00a45ef97dab2929294414c1b5/strict.lua#L12)

**Comment by thegrb93** [comment]
Kind of looks like this PR will obsolete the DebugTraceback.lua. The others look like very simple fixes.

**Comment by Vurv78** [comment]
Turns out CSharp.glua already fixed their compat and I don't really care about DebugTraceback so I think this is fine to merge without the old functions. Also none of these projects use the exact global function repeatedly so they are all easy patches. (Debug library doc says "Lua os library" though)

**Pull request merged**
