### PR TITLE
Divide string.rep C calls into multiple calls

### PR DESCRIPTION
**Pull request by edgarasf123**

### CODE REVIEW

**Comment by thegrb93** [comment]
Never do str = str .. "mystr" in lua. It is thousands of times slow than table.concat. Here's cleaner version.
```
local rep_chunk = 1000000
function string_methods.rep(str, rep, sep)
	local ret = {}
	for i = 1, rep / rep_chunk do
		ret[i]=string.rep(str, rep_chunk, sep)
	end
	ret[#ret+1] = string.rep(str, rep % rep_chunk, sep)
	return table.concat(ret, sep)
end
```

**Comment by edgarasf123** [comment]
Ok, I replaced it to use table.concat. Although I have included few checks to replicate the behavior of original function.

**Comment by edgarasf123** [comment]
I've also tested your code against original function, and it failed on some values such as negatives and when rep is same as rep_chunk. (I have set rep_chunk to 100 for testing purposes)

```
for i=-10,500,0.2 do
    local args = {"abc", i, "|"}
        
    local rep0 = string.rep(unpack(args))
    local rep1 = string_methods.rep1(unpack(args))
    local rep2 = string_methods.rep2(unpack(args))
    
    if rep1 ~= rep0 then
        print("rep1 != rep0 ("..i..")")
    end
    if rep2 ~= rep0 then
        print("rep2 != rep0 ("..i..")")
    end
end
```

**Comment by thegrb93** [comment]
Ok thx. Looks good.

**Pull request merged**
