### PR TITLE
Fix NextBot OnIgnite callback and update callback argument docs

### PR DESCRIPTION
**Pull request by adamnejm**
NextBots didn't pass themselves as the first callback argument as stated in the docs.
Also fixes `OnIgnite` callback not working.  
  
Fixes: #1381

### CODE REVIEW

**Comment by thegrb93** [comment]
It's by design that they don't pass self because each bot gets its own callback function.

**Comment by thegrb93** [comment]
We can keep the OnIgnite fix but I think the rest should be reverted.

**Comment by adamnejm** [comment]
IMO it's still nice when something passes itself to the callback, because then you can assign one function to multiple nextbots and differentiate between them, but sure.  

I'll modify it to only include the OnIgnite fix soon.

**Comment by adamnejm** [comment]
Done, also updated documentation so now it correctly reflects what arguments are passed.

**Pull request merged**
