### PR TITLE
Added optional parameter to loadstring for setting identity

### PR DESCRIPTION
**Pull request by Damianu**
Didnt have to test security of it, but seems to be fine as it's used only to handle errrors.
Edit: Well actually ran few tests and only thing I found is that this should make sure there is "SF: " before that identifier, otherwise its fine.

### CODE REVIEW

**Comment by thegrb93** [comment]
Why's the SF: needed?

**Comment by Damianu** [comment]
So its not confusing, SF: part is not shown in console anyway, also it might be just coincidence, but while testing while true do end it actually frozen my game while when there was no SF: 2 times, and didnt without it. It was weird, like we actually depend on this?

**Comment by thegrb93** [comment]
the loadstring error won't reach that though.

**Comment by thegrb93** [comment]
Not sure if thats required though. I'll check in a minute.

**Comment by thegrb93** [comment]
I did a huge refactor of error handling, can you test it real quick?

**Pull request merged**
