### PR TITLE
Added textures loaded from data

### PR DESCRIPTION
**Pull request by Damianu**
Closes https://github.com/thegrb93/StarfallEx/issues/238

I tested it a bit, tried JS injection and I think that my check works. Added checktype just because that function is quite slow anyway and shouldnt be called more than once per texture, so it's better to have stacktrace saying whats wrong. Textures have limit of 500kb, as I didnt see even slightest FPS drop on those, otherwise you would be able to put some 2mb image there and it'd freeze awesomium. It allows SVG etc too.

### CODE REVIEW

**Comment by Damianu** [comment]
I'll rebase it tommorow to get rid of git log spam(Or just squash&merge it as its feature branch).

**Comment by thegrb93** [comment]
use [^%w/+=] for the illegal characters and get rid of the print. Also I think the size limit should be 5MiB or 10MiB.

**Comment by thegrb93** [comment]
Looks good, can you just update the render.getTextureID documentation?

**Comment by Damianu** [comment]
Sure thing

**Pull request merged**
