### PR TITLE
Added prop.createSeat function

### PR DESCRIPTION
**Pull request by SubArrest**
I added e2's spawnSeat function from propcore which allows you to change the model of the seat while keeping its functionality (which creating a seat using prop.createSent doesn't allow you to change its model) and tested it on my test server.

As far as I know it seems to work fine but if anything is odd in the way I've coded let me know since I haven't properly committed to sf before.

### CODE REVIEW

**Comment by thegrb93** [comment]
We use tabs instead of spaces. I can check it out tonight.

**Comment by SubArrest** [comment]
other way around* I meant that it was spaces used instead of tabs in a section I noticed and I fixed it, but thx

**Comment by thegrb93** [comment]
It's currently spaces instead of tabs :v

**Comment by SubArrest** [comment]
oh rip, guess my ide replaced them as spaces automatically

**Pull request merged**
