### PR TITLE
add setPlayerColor for cl holos

### PR DESCRIPTION
**Pull request by ZH-Hristov**
this method of doing it doesn't work on serverside

### CODE REVIEW

**Comment by adamnejm** [comment]
Would be nice if the argument was just a normal color object.

**Comment by adamnejm** [comment]
Also, how about this  
  
`lua/starfall/libs_sh/entities.lua#204`
```lua
local playerColorWhitelist = {
	["prop_ragdoll"]       = true,
	["starfall_cnextbot"]  = true,
	["starfall_hologram"]  = true,
	["gmod_wire_hologram"] = true,
}
--- Sets the sheet color of a player-model
-- Can only be used on ragdolls, holograms and Starfall NextBots
-- @client
-- @param Color clr RGB color to use, alpha not supported
function ents_methods:setPlayerColor(clr)
	local ent = getent(self)
	if not playerColorWhitelist[ent:GetClass()] then SF.Throw("The entity isn't whitelisted", 2) end
	checkpermission(instance, ent, "entities.setRenderProperty")
	
	clr = cunwrap(clr)
	local vec = Vector(clr.r / 255, clr.g / 255, clr.b / 255)
	ent.GetPlayerColor = function() return vec end
end
```

**Comment by ZH-Hristov** [comment]
Whitelist is good idea. The reason it's a Vector is because that's what the function expects.

**Comment by ReasonableScripts** [comment]
When might this get merged? working on code that could really use this

**Comment by thegrb93** [comment]
I think player and bot support would be good to be added before it's merged.

**Comment by adamnejm** [comment]
> I think player and bot support would be good to be added before it's merged.

Made him a PR with the code I've sent above
https://github.com/ZH-Hristov/StarfallEx/pull/1

**Comment by ReasonableScripts** [comment]
yeah, that'd be best considering that's what I intend to use it for

**Pull request merged**
