### PR TITLE
Fix assert return values

### PR DESCRIPTION
**Pull request by Python1320**
Asserts should return the values they are passed

### CODE REVIEW

**Comment by thegrb93** [comment]
I wonder why we're not just using the lua assert function.

**Comment by Damianu** [comment]
This one uses SF.Throw with custom stacktrace level, at least looks like reason for that

**Comment by thegrb93** [comment]
Yeah I think it's legacy code since their error handler didn't correctly make a stack trace.

**Comment by thegrb93** [comment]
Ah no, 'error' was done this way because otherwise the 'level' argument wouldn't work. I think assert can be vanilla lua assert.

**Comment by thegrb93** [comment]
Nvm, not sure. I'll fix it up.

**Comment by thegrb93** [comment]
Uses vanilla lua functions now.

**Pull request merged**
