### PR TITLE
Allow using setEyeAngles on self

### PR DESCRIPTION
**Pull request by PolySteam**
Fix for being unable to modify own eye angles due to world entity owning players via CPPI.

### CODE REVIEW

**Comment by ANormalTwig** [comment]
I feel like this is more an issue with the prop protection you're using and not Starfall.
Not sure but I think requiring a player to be owned by themself via CPPI is intentional.

Also don't use GLua specific operators. Use `~=` instead of `!=`.

**Comment by PolySteam** [comment]
It happens with npp, fpp and spp. Player being owned by world has been a standard for more than a decade.

**Comment by Vurv78** [comment]
This is intentional to avoid aimbot.

**Comment by Vurv78** [comment]
Anyway if this is changed it should be changing the permissions, not hacking it into the function.

**Comment by adamnejm** [comment]
We essentially need a system for server-controlled permissions for clients.

**Comment by thegrb93** [comment]
We do exceptions for a lot of functions, essentially letting the player access themself but not others, so I don't see a problem with this. However, I think it should still be possible for this function to be disabled. I can take a look into adding another permission provider that does this.

**Comment by thegrb93** [comment]
Also shouldn't setEyeAngles be in the entities.lua? I thought this function worked on NPCs and Hologram npc models.

**Comment by thegrb93** [comment]
I just looked and we did add a middle-ground. You'll need the server to set the cvar `sf_permissions_entity_owneraccess 1`

**Pull request closed without merging**
