### PR TITLE
Added builtins.crcSource

### PR DESCRIPTION
**Pull request by adamnejm**
Any checks needed?
Didn't have a better idea for the function name, but can change if you want.

### CODE REVIEW

**Comment by adamnejm** [comment]
Ignore (second one today, nice)
You can do getScripts() and run that through crc() so this is more or less redundant

**Comment by thegrb93** [comment]
Use `crc(getScripts().YourScript)`. Also, mainfile isn't the current script.

**Comment by thegrb93** [comment]
Ah you beat me to that

**Comment by adamnejm** [comment]
Ha!

**Pull request closed without merging**
