### PR TITLE
Give users the option to allow 2d sounds

### PR DESCRIPTION
**Pull request by TheFreezebug**
Add a permission for playing 2d sounds instead of forcing 3d

### CODE REVIEW

**Comment by thegrb93** [comment]
Need to make it so someone can't trick it by putting an invalid flag with 3d in it, like fuck3d

**Comment by CornerPin** [comment]
It still doesn't check for 3D flag correctly
```Lua
local flags = "mono lol3d"
local is3d = flags:find("%s?3d%s?")

print( is3d ) -- 9, but there is no "3d" tag
```

Maybe this condition will be better?
```Lua
if not string.lower( " " .. flags ):find( "%f[%S]3d%f[%s%z]" ) then
```

**Comment by thegrb93** [comment]
That's interesting, I didn't know about an %f class. My suggestion was this,
```
local found3d = false
for s in string.gmatch("%S+") do
    if s=="3d" then
        found3d = true
        break
    end
end
```

**Comment by CornerPin** [comment]
It is frontier pattern and it was undocumented until Lua 5.2. Here is a good article about it http://lua-users.org/wiki/FrontierPattern

**Comment by Damianu** [comment]
Just for future reference: dont add spaces between ( )
@its-suun fx it

**Comment by thegrb93** [comment]
@Damianu I think my commits fix that

**Comment by Damianu** [comment]
Yeah I noticed it after writing that comment

**Pull request merged**
