### PR TITLE
Added sf_holograms_showowners

### PR DESCRIPTION
**Pull request by Damianu**
https://github.com/thegrb93/StarfallEx/issues/153

### CODE REVIEW

**Comment by Damianu** [comment]
http://s.damianu.me/NightSorbet <- How it looks, kinda same thing as wire uses

**Comment by thegrb93** [comment]
This can be done 200000% more efficiently by using the hologram draw hook. I'll get around to it soon.

**Comment by thegrb93** [comment]
Nvm, invisible holograms won't show the owner. I'll optimize those code though and make the owner show when context menu is open instead of console command.

**Comment by Damianu** [comment]
I think that context menu is a bad idea, if you want to use context menu + holos for example.

**Comment by thegrb93** [comment]
Also CPPIGetOwner is serverside only.

**Comment by Damianu** [comment]
So we probbably should just leave SetNWEntity thing?

**Pull request merged**
