### PR TITLE
Add --@includedata directive

### PR DESCRIPTION
**Pull request by x4fx77x4f**
I hope I'm not being a nuisance with these PRs. Adds an `--@includedata` directive to allow including files, but without attempting to compile or process directives for those files. Useful for including non-script files, and will allow for some chips to avoid the whole roundabout process of uploading the assets online and downloading them again at runtime.

Tests:
`includedata.txt`:
```lua
--@shared
--@includedata invalidsyntax.txt
local a = getScripts()['invalidsyntax.txt']
--print(a)
assert(a, "not working :(")
assert(not getScripts()['invalidsyntax2.txt'], "almost working :|")
print("it works :)")
```
`invalidsyntax.txt`:
```lua
--@include invalidsyntax2.txt
--@invalid
lolol invalid syntax
```
`invalidsyntax2.txt`:
```lua
LOLOL INVALID SYNTAX AGAIN!!!!
```

Practical example:
```lua
--@client
--@includedata chopsrampage/chopper.obj
--@includedata chopsrampage/palette.png
-- Load a model of a helicopter and display it.
local data = getScripts()
local obj = data['chopsrampage/chopper.obj']
local matpath = file.writeTemp('palette.png', data['chopsrampage/palette.png'])
local mat = material.createFromImage('../'..matpath, '')
local threshold = quotaMax()*0.5
local thread = coroutine.create(function()
    return mesh.createFromObj(obj, true, true)
end)
hook.add('think', 'init', function()
    while quotaUsed() < threshold do
        local tbl = coroutine.resume(thread)
        if tbl then
            hook.remove('think', 'init')
            local vmtx = {
                w = 1024,
                h = 1024,
                type = '3D',
                origin = Vector(0, -10, 0),
                angles = Angle(0, 90, 0),
                fov = 70,
                aspect = 1
            }
            render.createRenderTarget('out')
            hook.add('render', '', function()
                render.selectRenderTarget('out')
                    render.pushViewMatrix(vmtx)
                        render.setFilterMag(TEXFILTER.POINT)
                        render.setMaterial(mat)
                        tbl.chopper:draw()
                    render.popViewMatrix()
                render.selectRenderTarget()
                render.setRenderTargetTexture('out')
                render.drawTexturedRect(0, 0, 512, 512)
            end)
            return
        end
    end
end)
```
Screenshot
(Ignore the rendering bugs)

### CODE REVIEW

**Comment by thegrb93** [comment]
Looks good. Will need to make sure duplicator works with these.

**Comment by x4fx77x4f** [comment]
Didn't even think to test that. Works okay with vanilla Duplicator and Advanced Duplicator 2.

**Comment by thegrb93** [comment]
This I think I can fully review and merge today. I have a busy week. Your other PR I'm very unsure about the new directive. Not a fan of toggling features with a directive. I think there may be a fast solution.

**Comment by x4fx77x4f** [comment]
Hopefully.

**Review by thegrb93 — APPROVED** [review]

**Pull request merged**
