### PR TITLE
Added PreDrawViewModels Hook

### PR DESCRIPTION
**Pull request by ReasonableScripts**
Tested and appears to function as intended

### CODE REVIEW

**Comment by ReasonableScripts** [comment]
I dont know how or why it counts as all the lines being additions, but the actual addition starts at 293

**Comment by ReasonableScripts** [comment]
i'm not extremely familiar with github so I dont know what i did wrong to make it count everything as a new addition

**Comment by ANormalTwig** [comment]
You put the entire render file including your additions in the base directory.

**Comment by ReasonableScripts** [comment]
Oh i forgot to switch to the branch i made oops

**Comment by ReasonableScripts** [comment]
wait no, i did switch

**Comment by ReasonableScripts** [comment]
i dont know how else i was supposed to add the code, i'm using the website github

**Comment by ReasonableScripts** [comment]
How do i add it without adding the entire file?

**Pull request closed without merging**
