### PR TITLE
VGUI Library

### PR DESCRIPTION
**Pull request by ZH-Hristov**
Yes I accidentally deleted the branch (again)

### CODE REVIEW

**Comment by TheVayt** [comment]
You may try to find unreachable commits with `git reflog` / `git log --walk-reflogs` and reset your branch to that state with `git reset`. Or use some kind of GUI like git graph extension for vscode with showing commits only mentioned by reflogs.

**Comment by ZH-Hristov** [comment]
ehhhhhhhhhhhhh nnnnnnnnnnnnnnnaaaaaaaaaah

**Comment by Vurv78** [comment]
Also please use a feature branch for this stuff next time, its even on the PR template text

**Comment by thegrb93** [comment]
I'm going to do a bit of cleanup to this before I merge it. I think putting each type and its methods each in their own block will make it a lot cleaner.

**Comment by ANormalTwig** [comment]
When is this going to get added.

Also I think having separate functions for creating each panel type would bloat the docs a little.

**Comment by adamnejm** [comment]
*Updated docs to perform search after 5 letters instead of 3 due to rendering lags*

**Comment by thegrb93** [comment]
I think I'd like this to be a module the player can add to their own starfall install, and I'd like the docs to only populate with these things if they have it enabled. similar to joystick/luasocket. I need to figure out how to do that though.

**Pull request closed without merging**
