### PR TITLE
Add 'PlayerSpawnProp' check in `prop.createComponent`

### PR DESCRIPTION
**Pull request by adamnejm**
The `prop.createComponent` was missing these 2 calls for some reason.

### CODE REVIEW

**Comment by thegrb93** [comment]
Components are sents, not prop

**Comment by adamnejm** [comment]
Oh right, fixed.

**Comment by thegrb93** [comment]
The reason we don't do it is because it influences the player's SENT count.

**Comment by adamnejm** [comment]
I see, Wire Gates don't do it as well. The first call should remain though, right? So admin mods and other addons can have granular control over what the player is allowed to spawn.

**Pull request merged**
