### PR TITLE
Workaround for `setTextureURL` not working on branches with Awesomium

### PR DESCRIPTION
**Pull request by stepa2**
- Refactored URL texture queue system.
- Adds workaround for `setTextureURL`.

Basically, I load the image with `http.Fetch`, convert data to Base64 and then load texture from `data:` URL.

### CODE REVIEW

**Comment by thegrb93** [comment]
I'd prefer a class based approach rather than a bunch of fragmented local functions. (current code uses 'closure' based approach)

**Comment by thegrb93** [comment]
If you want to just add your fix without the refactor, I can refactor it to use classes sometime.

**Comment by stepa2** [comment]
I would prefer to not refactor it in this PR

**Comment by thegrb93** [comment]
```lua


local HttpTextureLoader = {}
local HttpTexture = {
    __index = {
        load = function(self)
            if self.error then return end
            if self.instance.error then self:error() return end

            HttpTextureLoader.Panel:AddFunction("sf", "imageLoaded", function(w, h) timer.Simple(0, function() self:onload(w, h) end) end)
            HttpTextureLoader.Panel:AddFunction("sf", "imageErrored", function() timer.Simple(0, function() self:error() end) end)
            HttpTextureLoader.Panel:RunJavascript(
            [[img.removeAttribute("width");
            img.removeAttribute("height");
            img.style.left="0px";
            img.style.top="0px";
            img.src="]] .. string.JavascriptSafe( self.url ) .. [[";]]..
            (BRANCH == "unknown" and "\nif(img.complete)renderImage();" or ""))
            HttpTextureLoader.Panel:Show()
        end,

        onload = function(self, w, h)
            if self.error then return end
			if self.instance.error then self:error() return end
            if self.usedlayout then self:render() return end

            if self.callback then
                self.callback(w, h, function(x,y,w,h,pixelated)
                    self:layout(x,y,w,h,pixelated)
                end, false)
            end

            if not self.usedlayout then
                self.usedlayout = true
                self:render()
            end
        end,

        layout = function(self,x,y,w,h,pixelated)
            if self.usedlayout then SF.Throw("You can only use layout once", 3) end
            checkluatype(x, TYPE_NUMBER, 2)
            checkluatype(y, TYPE_NUMBER, 2)
            checkluatype(w, TYPE_NUMBER, 2)
            checkluatype(h, TYPE_NUMBER, 2)
            if pixelated~=nil then checkluatype(pixelated, TYPE_BOOL, 2) end
            self.usedlayout = true
            HttpTextureLoader.Panel:RunJavascript([[
                img.style.left=']]..x..[[px';img.style.top=']]..y..[[px';img.width=]]..w..[[;img.height=]]..h..[[;img.style.imageRendering=']]..(pixelated and "pixelated" or "auto")..[[';
                renderImage();
            ]])
        end,

        render = function(self)
            hook.Add("PreRender","SF_HTMLPanelCopyTexture",function()
                HttpTextureLoader.Panel:UpdateHTMLTexture()
                local mat = HttpTextureLoader.Panel:GetHTMLMaterial()
                if mat then
                    render.PushRenderTarget(self.texture)
                        render.Clear(0, 0, 0, 0, false, false)
                        cam.Start2D()
                        surface.SetMaterial(mat)
                        surface.SetDrawColor(255, 255, 255)
                        surface.DrawTexturedRect(0, 0, 1024, 1024)
                        cam.End2D()
                    render.PopRenderTarget()
                end
                hook.Remove("PreRender","SF_HTMLPanelCopyTexture")
                timer.Simple(0, function() self:done() end)
            end)
        end,
        
        error = function(self)
            if self.error then return end
            self.error = true
            if self.callback then self.callback() end
            HttpTextureLoader.pop()
        end,

        done = function(self)
            if self.error then return end
            self.error = true
            if self.donecallback then self.donecallback() end
            HttpTextureLoader.pop()
        end
    },
    __call = function(t, instance, texture, url, callback, donecallback)
        return setmetatable({
            instance = instance,
            texture = texture,
            url = url,
            callback = callback,
            donecallback = donecallback,
            usedlayout = false,
            error = false,
        }, t)
    end
}
setmetatable(HttpTexture, HttpTexture)

local HttpTextureLoader = {}
HttpTextureLoader.Queue = {}

function HttpTextureLoader.initialize()
    local Panel = SF.URLTextureLoader
    if not Panel then
        Panel = vgui.Create("DHTML")
        Panel:SetSize(1024, 1024)
        Panel:SetAlpha(0)
        Panel:SetMouseInputEnabled(false)
        Panel:SetHTML(
        [[<html style="overflow:hidden"><body><script>
        if (!requestAnimationFrame)
            var requestAnimationFrame = webkitRequestAnimationFrame;
        function renderImage(){
            requestAnimationFrame(function(){
                requestAnimationFrame(function(){
                    document.body.offsetWidth
                    requestAnimationFrame(function(){
                        sf.imageLoaded(img.width, img.height);
                    });
                });
            });
        }
        var img = new Image();
        img.style.position="absolute";
        img.onload = renderImage;
        img.onerror = function (){sf.imageErrored();}
        document.body.appendChild(img);
        </script></body></html>]])
        Panel:Hide()
        SF.URLTextureLoader = Panel
    end
    HttpTextureLoader.Panel = Panel
end

function HttpTextureLoader.request_preInit(request)
    HttpTextureLoader.initialize()
    HttpTextureLoader.request = HttpTextureLoader.request_postInit
    HttpTextureLoader.request(request)
end
HttpTextureLoader.request = HttpTextureLoader.request_preInit

function HttpTextureLoader.request_postInit(request)
    local len = #HttpTextureLoader.Queue
    HttpTextureLoader.Queue[len + 1] = request
    if len==0 then HttpTextureLoader.nextRequest() end
end

function HttpTextureLoader.nextRequest()
    local request = HttpTextureLoader.Queue[1]
    request:load()
    timer.Create("SF_URLTextureTimeout", 10, 1, function() request:error() end)
end

function HttpTextureLoader.pop()
    table.remove(HttpTextureLoader.Queue, 1)
    if #HttpTextureLoader.Queue > 0 then
        HttpTextureLoader.nextRequest()
    else
		timer.Remove("SF_URLTextureTimeout")
		HttpTextureLoader.Panel:Hide()
    end
end
```

**Pull request closed without merging**
