### PR TITLE
Fix starfall_prop's rendering above other close entities and effects

### PR DESCRIPTION
**Pull request by UnrealEugene**
Related issue: https://github.com/thegrb93/StarfallEx/issues/1420

### CODE REVIEW

**Comment by thegrb93** [comment]
Neither wire and starfall holograms should have this in the Draw hook. Not good for performance.

**Comment by UnrealEugene** [comment]
> Neither wire nor starfall holograms should have this in the Draw hook. Not good for performance.

Custom props and holograms already use `RENDERGROUP_BOTH`, so it means they are drawn two times instead of one when they have 255 alpha (which is arguably the most frequent value). It's actually noticeable when hundreds of holograms are drawn.

What about changing `RenderGroup` inside `Entity:setColor()` function when opaqueness is changed and custom mesh is set?

**Comment by thegrb93** [comment]
That sounds better.

**Comment by UnrealEugene** [comment]
Though it will be tricky to set `RenderGroup` if `Entity:setColor()` called server-side.

**Comment by UnrealEugene** [comment]
> Though it will be tricky to set `RenderGroup` if `Entity:setColor()` is called server-side.

Well, I think it's impossible to set `RenderGroup` based on server-side change of color without either networking (which is obviously bad here since color can be changed every tick) or using render hooks. So I guess there is no other choice but to put `RenderGroup` change inside `ENT:Draw()` hook. It will provide significant fps boost for opaque holograms/custom props and negligible fps decline in transparent case.

**Comment by thegrb93** [comment]
This should also be done for starfall_prop too right?

**Comment by UnrealEugene** [comment]
> This should also be done for starfall_prop too right?

Yeah, they both have same issue.

**Comment by thegrb93** [comment]
What happens if you use `RENDERGROUP_TRANSLUCENT` instead of `RENDERGROUP_BOTH`?

**Comment by thegrb93** [comment]
I think putting this in the draw method is really bad. I'd bug the gmod devs for a better fix.

**Comment by UnrealEugene** [comment]
> What happens if you use `RENDERGROUP_TRANSLUCENT` instead of `RENDERGROUP_BOTH`?

I seems it doesn't change anything. Even with `RENDERGROUP_BOTH` transparent entities with `RENDERMODE_TRANSALPHA` set are already drawn only once, so changing it will have no fps increase.

**Pull request merged**
