### PR TITLE
Whitelist builtin libraries

### PR DESCRIPTION
**Pull request by edgarasf123**
Just to be safe in case of gmod updates, where functions could be added that returns unwrapped objects.
Like string.ToColor for instance.

### CODE REVIEW

**Comment by Damianu** [comment]
Nice one

**Comment by thegrb93** [comment]
We're these lists made by iterating over the library? (Need to be sure nothing was forgotten)

**Comment by edgarasf123** [comment]
I copy/paste it from wiki.garrysmod.com. Then ran some regex to get it into table format.

**Comment by thegrb93** [comment]
I wouldn't trust the wiki. Let me generate a list with vanilla gmod. Also, you don't need the functions we manually define in the list.

**Comment by thegrb93** [comment]
```
- string -
Comma
EndsWith
Explode
FormattedTime
GetChar
GetExtensionFromFilename
GetFileFromFilename
GetPathFromFilename
Implode
JavascriptSafe
Left
NiceSize
NiceTime
PatternSafe
Replace
Right
SetChar
Split
StartWith
StripExtension
ToMinutesSeconds
ToMinutesSecondsMilliseconds
ToTable
Trim
TrimLeft
TrimRight
byte
char
dump
find
format
gfind
gmatch
gsub
len
lower
match
reverse
sub
upper

- math -
AngleDifference
Approach
ApproachAngle
BinToInt
Clamp
Dist
Distance
EaseInOut
IntToBin
Max
Min
NormalizeAngle
Rand
Remap
Round
TimeFraction
Truncate
abs
acos
asin
atan
atan2
calcBSplineN
ceil
cos
cosh
deg
exp
floor
fmod
frexp
huge
ldexp
log
log10
max
min
mod
modf
pi
pow
rad
random
randomseed
sin
sinh
sqrt
tan
tanh

- os -
clock
date
difftime
time

- table -
Add
ClearKeys
CollapseKeyValue
Copy
CopyFromTo
Count
DeSanitise
Empty
FindNext
FindPrev
ForEach
ForceInsert
GetFirstKey
GetFirstValue
GetKeys
GetLastKey
GetLastValue
GetWinningKey
HasValue
Inherit
IsSequential
KeyFromValue
KeysFromValue
LowerKeyNames
Merge
Random
RemoveByValue
Reverse
Sanitise
SortByKey
SortByMember
SortDesc
ToString
concat
foreach
foreachi
getn
insert
maxn
remove
sort

- bit -
arshift
band
bnot
bor
bswap
bxor
lshift
rol
ror
rshift
tobit
tohex
```

**Comment by thegrb93** [comment]
Nevermind I guess the wiki is generated from vanilla gmod.

**Comment by thegrb93** [comment]
Okay, the default libraries are defined explicitly now. Thanks for the report though.

**Pull request closed without merging**
