### PR TITLE
SF.DefaultEnvironment.printMessage()

### PR DESCRIPTION
**Pull request by redpr1sm**
Clientside Player:PrintMessage() function.

### CODE REVIEW

**Comment by thegrb93** [comment]
Can you put it somewhere in the if block at line 231 so it is with the other clientside functions?

**Comment by thegrb93** [comment]
You removed it?

**Comment by redpr1sm** [comment]
Was on mobile this morning. The source editor on the iOS app I use is really crappy.

**Comment by redpr1sm** [comment]
Done. Finally.

**Pull request merged**
