### PR TITLE
fix ply:hasGodMode() not returning properly

### PR DESCRIPTION
**Pull request by redpr1sm**
also changed return desc to match other methods' formatting

### CODE REVIEW

**Comment by thegrb93** [comment]
Can you make it, 'return IsValid(ent) and ent:HasGodMode() or false'?

**Comment by redpr1sm** [comment]
Will do as soon as I get home. Should be an hour or so.

**Comment by edgarasf123** [comment]
Also, on wiki it says it shared, why is this serverside?

**Comment by redpr1sm** [comment]
Apparently it doesn't work on client despite it saying shared. Don't know why.

**Comment by redpr1sm** [comment]
Added stuff as requested. If there are no more issues then merge I guess

**Pull request merged**
