### PR TITLE
Added shared holograms example, fixes: #887

### PR DESCRIPTION
**Pull request by adamnejm**
- Creation of serverside and clientside holograms
- Transmitting holograms from server to client
- Converting to holograms from entities
- Usage of cl methods on cl holos
- Usage of cl methods on sv holos
- Simple matrix usage
- ~~Explains how certain methods might not be available~~
- Manual fixing of cl holo's render bounds
- Why am i writing this, go read code ;f
- Basic networking
- ~~Simplified explanation and possible fix to invalid entity when networking~~

### CODE REVIEW

**Comment by thegrb93** [comment]
Only problem here is net.readEntity() may return invalid entity in which case you need to ask the server to send the hologram again.

**Comment by thegrb93** [comment]
I may add a net.readCreatedEntity(callback) which will invoke the callback whenever the send entity-id is valid.

**Comment by adamnejm** [comment]
Well I mean, dunno if polluting simple example as this one is worth it, I added a side note explaining why it may be happening and even provided a solution that tells you it's better to send the entity ID, not enough?

**Comment by thegrb93** [comment]
We need a pattern that works 100% of the time. Even my own chips have hit this problem and its annoying af.

**Comment by thegrb93** [comment]
How about it keeps requesting the hologram for server until it gets a valid one.

**Comment by thegrb93** [comment]
Nvm that idea is wasteful to net.

**Comment by adamnejm** [comment]
That works, but I don't see it as the best solution.
IMO you should ... ye

**Comment by adamnejm** [comment]
I will just put it in a very simple checking loop either a hook or a timer and see if ent is valid, then will initialize the scale thingy

**Comment by adamnejm** [comment]
I don't like how it turned out, it doesn't show how you can scale it up to include more entities being sent, but meh... it is what it is. Good enough for a simple example i think

**Comment by thegrb93** [comment]
Hows this?

**Comment by adamnejm** [comment]
Pretty sweet, ngl
also missing isvalid check inside of the tick hook, right?

**Comment by adamnejm** [comment]
this will make the script not error, but has no fallback to call for the entity again once user re-enters the pvs for example

**Comment by thegrb93** [comment]
I think once the entity is created, it's always created.

**Comment by adamnejm** [comment]
Not sure, but it can be true.
Anyway, the check still applies since it will prevent crashing of the past instance when reuploading script

**Pull request merged**
