### PR TITLE
A few small fixes

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #1703
Fixes: #1704
Fixes: #1705

### CODE REVIEW

**Comment by thegrb93** [comment]
Idk if this fixes all of the errors, but let me know if more occur or if this makes anything stop working. @wrefgtzweve

**Comment by legokidlogan** [comment]
[This line](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/editor.lua#L773) now occasionally errors with `Tried to use a NULL entity!`

**Comment by wrefgtzweve** [comment]
> [This line](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/editor.lua#L773) now occasionally errors with `Tried to use a NULL entity!`

That is one of the fixed bugs see https://github.com/thegrb93/StarfallEx/issues/1704#event-12412303865

**Comment by legokidlogan** [comment]
Oh right, update didn't apply to the server yet. All good then.

**Comment by wrefgtzweve** [comment]
Im still seeing this error happening
```
[starfallex] addons/starfallex/lua/entities/starfall_processor/cl_init.lua:146: attempt to call method 'Destroy' (a nil value)
  1. setup - addons/starfallex/lua/entities/starfall_processor/cl_init.lua:146
   2. callback - addons/starfallex/lua/entities/starfall_processor/cl_init.lua:154
    3. callback - addons/starfallex/lua/starfall/sflib.lua:1145
     4. func - addons/starfallex/lua/starfall/sflib.lua:1125
      5. unknown - addons/ulib/lua/includes/modules/hook.lua:260
```

**Comment by thegrb93** [comment]
@wrefgtzweve let me know if it's fixed.

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/pull/1708

**Comment by wrefgtzweve** [comment]
I havent seen the error happen yet but i did see this one happen
```
[starfallex] addons/starfallex/lua/entities/starfall_processor/cl_init.lua:146: attempt to call method 'SetupFiles' (a nil value)
  1. setup - addons/starfallex/lua/entities/starfall_processor/cl_init.lua:146
   2. callback - addons/starfallex/lua/entities/starfall_processor/cl_init.lua:153
    3. callback - addons/starfallex/lua/starfall/sflib.lua:1145
     4. func - addons/starfallex/lua/starfall/sflib.lua:1125
      5. unknown - addons/ulib/lua/includes/modules/hook.lua:260
```

**Comment by thegrb93** [comment]
@wrefgtzweve https://github.com/thegrb93/StarfallEx/pull/1711 should hopefully fix it

**Comment by wrefgtzweve** [comment]
👍 I'll keep an eye out

**Pull request merged**
