### PR TITLE
Added render.clearDepth

### PR DESCRIPTION
**Pull request by CornerPin**
Added render.clearDepth because using render.clear also clears render target

### CODE REVIEW

**Comment by thegrb93** [comment]
This isnt a safe function to use outside of rendertargets. Also this already exists with render.clear

**Comment by CornerPin** [comment]
But user may want to clear only depth buffer, render.clear always clears render target.

**Comment by thegrb93** [comment]
I see. Can you put the same checks that render.clear uses though. It's still not safe to be used alone.

**Comment by thegrb93** [comment]
Nvm I see the changes now. Can you do one more thing and move it next to render.clear for consistency. Thanks.

**Comment by thegrb93** [comment]
Nvm, next to enableDepth is fine.

**Pull request merged**
