### PR TITLE
fix auto indenting

### PR DESCRIPTION
**Pull request by Divran**
the auto indent convar is now checked (previously was always enabled no matter what)
pressing enter after "then" now indents
pressing enter after "do" now indents
pressing enter after "repeat" now indents
pressing enter after "{" now indents
typing "}" now auto un-indents properly (previously it did it incorrectly)
typing "end" now auto un-indents, and then if you type something else like "endd" immediately after, it re-indents for you
typing "until" now auto un-indents, and then if you type something else like "untild" immediately after, it re-indents for you

# Before creating pull request
- Move all changes to **separate** branch (Don't use master of your fork).
- **Don't** reuse branches.
- **Don't** sync that branch after creating pull request unless it's really needed. (IE. upstream changed code structure).
- Test it and try fixing bugs ahead.
- If you know about any bugs, make sure to list them in PR message.
- Make sure pull request message informs about **ALL** the changes.
- Your pull request can be work-in-progress if you want others to help you with coding or give you  opinions, just make sure to state it's not ready.
- Try to avoid messing with whitespaces. (Setup your editor properly to follow our style).
- If you find whitespaces that don't follow our style you can fix them in separate commit.
- Read about [github flow](https://guides.github.com/introduction/flow/)
​

# Thank you

Thank you for contributing and helping StarfallEx community!

### CODE REVIEW

**Comment by Divran** [comment]
> Before creating pull request
Move all changes to separate branch (Don't use master of your fork).

oops

**Comment by thegrb93** [comment]
Seems to work perfectly. Makes using the in game editor a lot easier. The only thing missing now is the auto indent for new functions, but this is good enough for now

**Comment by adamnejm** [comment]
Bracket pair highlighting could also use some tweaking.  
IIRC they only highlight their respective pair when the caret is on the left side of the symbol. It would be nice if it highlighted the pairing when the cursor was also placed after the parenthesis.

**Comment by Derpius** [comment]
```lua
hook.add("somehook", "", function()

    end) -- the close bracket here shouldn't indent end
```

**Comment by Divran** [comment]
the quick and dirty fix to that is to just check for `)` in addition to `(` on this line
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/tabhandlers/tab_wire.lua#L1482

I can do it after the font editor PR is merged, which would allow me to delete my fork and start over and do it properly with separate branches instead of being an idiot and using the master branch

or @thegrb93 could fix it easily too

**Pull request merged**
