### PR TITLE
Standardize examples naming scheme

### PR DESCRIPTION
**Pull request by adamnejm**
Rename examples to snake_case and prefix beginner examples with `basic_`

### CODE REVIEW

**Comment by thegrb93** [comment]
I'm fine with the `basic_` prefix, but I think the names should still be camel case instead of snake case.

**Comment by adamnejm** [comment]
Weird, but even a convention that I don't find very pretty is better than than the absolute mess it is now.

**Comment by thegrb93** [comment]
Hmm, ok I think you're right. Sorry I didn't realize how many were already snakecase before. Probably better to delete that last commit and I'll merge.

**Comment by adamnejm** [comment]
Reverted to what I was initially suggesting.

**Pull request merged**
