### PR TITLE
fixed searchbar and other small improvements

### PR DESCRIPTION
**Pull request by adamnejm**
Deleted some leftovers from flexbox.
Fixed searchbar hiding below the sidebar children.
Fixed logo center alignment.
Fixed realm icons size decreasing.
Added hiding overflow (of the logo mostly) when sidebar gets too small.

### CODE REVIEW

**Comment by adamnejm** [comment]
This is not tested in game, somebody has to build it an check.
Apparently media queries are broken in awesomium when html tag has props, if this doesn't work I can come up with a different way to fix it.

**Comment by Damianu** [comment]
npm run build and replace starfall/html/sf_doc.html with build/index.html in order to test

**Comment by adamnejm** [comment]
As sparky said - it's not untrue that I'm lazy, why bother :>

**Comment by thegrb93** [comment]
Cuz making others test your code and finding it is broken is worse for your reputation.

**Comment by thegrb93** [comment]
I'll try it after I finish work

**Comment by thegrb93** [comment]
Didn't work. http://sparkysandbox.org/doc/

**Comment by thegrb93** [comment]
Adding 'min-width: 250px;' to the .sidebar class seems to work though.

**Comment by thegrb93** [comment]
Looks like the root cause is the Star icon in the title pushes stuff down.

**Comment by thegrb93** [comment]
I think that's the .logo class?

**Pull request merged**
